"use client";
import type { Metadata } from "next";
import Sidebar from "../sidebar/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
