"use client";
import LoginPage from "@/app/login/page";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RegisterLayout({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) {
  return <LoginPage />;
}
